### ISSUE TITLE
train the model

### ISSUE THREAD

**Issue by duxiangcheng** [Yuliang-Liu/bezier_curve_text_spotting#2]
Thanks for your contribution.
How to train the model. And how to get the training data,
Thanks

**Comment by Yuliang-Liu** [comment]
All code required for training is included in this repo.  Simply using train_net.py. 
All the training data are also publicly available. 
You will need to figure out "how" at this moment. We will release the instruction in the future.

**Comment by eyebies** [comment]
@Yuliang-Liu  Thanks for sharing the code! just wanted to check if the word_bezier.yaml needs any parameter changes for training? If I want to fine-tune from your model, what parameter changes would you recommend?
thanks!

**Comment by Yuliang-Liu** [comment]
An Example: 
```
OUTPUT_DIR: output/align/07x32
MODEL:
  META_ARCHITECTURE: "OneStage"
  ONE_STAGE_HEAD: "align"
  WEIGHT: "YOUR_MODEL"
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50"
  NECK:
    CONV_BODY: "fpn-align"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  ALIGN:
    POOLER_RESOLUTION: (7, 32)
    POOLER_CANONICAL_SCALE: 160
    POOLER_SCALES: (0.25, 0.125, 0.0625)
    PREDICTOR: "ctc" # "ctc" or "attention"
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
DATASETS:
  TRAIN: ("YOUR_TRAINSET",)
  TEST: ("YOUR_TESTSET",)
  TEXT:
    NUM_CHARS: 25
    VOC_SIZE: 97
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  FLIP_PROB_TRAIN: 0.0
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 180000)
  MAX_ITER: 250000
  IMS_PER_BATCH: 2
  WARMUP_METHOD: "constant"
  CHECKPOINT_PERIOD: 2500
TEST:
  IMS_PER_BATCH: 1
```

@eyebies Simply changing "ctc" to "attention" if you would like to fine-tune from the provided model.
